import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'react-perfect-scrollbar/dist/css/styles.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import ContextProviders from '@/@core/context/ContextProviders'
import { Toaster } from 'react-hot-toast'
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Toaster position='top-center' reverseOrder={false} />
        <NextTopLoader color={`#9155FD !important`} />

        <ContextProviders>{children}</ContextProviders>
      </body>
    </html>
  )
}
