import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

// ** Utils Imports

// ** React Perfect Scrollbar Style
import "react-perfect-scrollbar/dist/css/styles.css";

// ** Global css styles
import "bootstrap/dist/css/bootstrap.min.css";
import AppContextProviders from "@/@core/context/AppContextProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AppContextProviders>
        <body className={inter.className}>{children}</body>
      </AppContextProviders>
    </html>
  );
}
